#!/bin/bash
# install squid
cd;MYIP=$(wget -qO- ipv4.icanhazip.com)
wget -qO /etc/squid3/squid.conf "https://raw.githubusercontent.com/X-DCB/Unix/master/openvpn/squid.conf"
sed -i "s/yourip/$MYIP/g" /etc/squid3/squid.conf
echo Script by Dexter Cellona Banawon
echo "PHC - Granade :)"
