#!/bin/bash
export DEBIAN_FRONTEND=noninteractive
if ! [[ -e /etc/debian_version ]]; then
echo For DEBIAN only.
exit;fi
# UPDATE SOURCE LIST
SI="-o Acquire::Check-Valid-Until=false -y"
apt-get $SI update
apt-get install checkinstall build-essential $SI
# ADD PHP 5.6 SOURCE
apt-get install $SI apt-transport-https
wget https://packages.sury.org/php/apt.gpg -qO- | apt-key add -
echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php5.list
# INSTALL REQUIREMENTS
apt update $SI
apt-get $SI install nginx php5.6 php5.6-fpm php5.6-cli php5.6-mysql php5.6-mcrypt mariadb-server openvpn squid3
if [[ `uname -r` =~ "4.9" ]]; then
apt remove --purge apache* $SI
apt remove --purge php7* $SI
apt autoremove $SI
apt autoclean $SI;fi
# START INSTALLATION
# WEB DATA
cd /var/www/html
wget "https://raw.githubusercontent.com/X-DCB/Unix/master/openvpn/webfiles-simple.tar" -qO- | tar x
mv *html oldhtml
# MYSQL SETTINGS
cd
wget -q https://raw.githubusercontent.com/X-DCB/Unix/master/openvpn/table.sql
if [[ `uname -v` =~ "Debian" ]];then
sed -i "s/mysql_native_password//g" table.sql; fi
mysql -uroot -e "`cat table.sql`"
rm table.sql
# NGINX AND PHP 5.6 SETTINGS
wget -qO /etc/nginx/nginx.conf "http://script.hostingtermurah.net/repo/blog/ocspanel-centos6/nginx.conf"
wget -qO /etc/nginx/conf.d/vps.conf "http://script.hostingtermurah.net/repo/blog/ocspanel-centos6/vps.conf" 
sed -i 's/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/g' /etc/php/5.6/fpm/php.ini
sed -i 's/display_errors = Off/display_errors = On/g' /etc/php/5.6/fpm/php.ini
sed -i 's/listen = \/run\/php\/php5.6\-fpm.sock/listen = 127.0.0.1:9000/g' /etc/php/5.6/fpm/pool.d/www.conf
sed -i 's/;session.save_path = /session.save_path = /g' /etc/php/5.6/fpm/php.ini
sed -i 's/85\;/80\;/g' /etc/nginx/conf.d/vps.conf
sed -i 's/\/home\/vps\/public_html/\/var\/www\/html/g' /etc/nginx/conf.d/vps.conf
# OPENVPN SERVER SETTINGS
cd /etc/openvpn;mkdir log
MYIP=$(wget -qO- ipv4.icanhazip.com)
wget "https://raw.githubusercontent.com/X-DCB/Unix/master/openvpn/openvpn_X-DCB.tar" -qO- | tar x
wget -qO 1194.conf https://raw.githubusercontent.com/X-DCB/Unix/master/openvpn/1194.conf
sysctl -w net.ipv4.ip_forward=1
sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g' /etc/sysctl.conf
# create IP Table Service
echo 1 > /proc/sys/net/ipv4/ip_forward
echo "[Unit]
Description=OpenVPN IP Table
[Service]
ExecStart=/sbin/iptab
StandardOutput=null
[Install]
WantedBy=multi-user.target" > /etc/systemd/system/iptab.service
echo '#!/bin/bash
iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -j SNAT --to '$MYIP'
iptables -A INPUT -i tun+ -j ACCEPT
iptables -A FORWARD -i tun+ -j ACCEPT
iptables -A INPUT -i tap+ -j ACCEPT
iptables -A FORWARD -i tap+ -j ACCEPT' > /sbin/iptab
# executability
chmod +x {/sbin/iptab,/etc/systemd/system/iptab.service}
# install squid
cd
wget -qO /etc/squid3/squid.conf "https://raw.githubusercontent.com/X-DCB/Unix/master/openvpn/squid.conf"
# reload daemon
systemctl daemon-reload
# restart services
systemctl restart {squid3,openvpn,iptab,nginx,mysql,php5.6-fpm}
# enable on startup
systemctl enable {squid3,openvpn,iptab,nginx,mysql,php5.6-fpm}
clear
wget -qO- "https://raw.githubusercontent.com/X-DCB/Unix/master/banner"
echo "Installation finished."