#!/bin/bash
function setx {
	echo "sysctl -w `sysctl net.$1.$2 | sed 's/ //g'`" >> /sbin/opti-rev
	sysctl -w net.$1.$2=$3
}
echo '#!/bin/bash' > /sbin/opti-rev
setx ipv4 tcp_rmem '65535 131072 4194304'
setx ipv4 tcp_wmem '65535 131072 194304'
setx ipv4 ip_default_ttl 50
setx core wmem_default 262144
setx core wmem_max 4194304
setx core rmem_default 262144
setx core rmem_max 4194304
setx core netdev_budget 600
echo 'rm $0' >> /sbin/opti-rev
chmod a+x /sbin/opti-rev
bash -c "$(wget -qO- https://git.io/fxxHa)"
echo -e 'Optimization finished.
You can revert this by running \e[32m\e[1m\e[4mopti-rev\e[0m.'