#!/bin/bash
MYIP=$(wget -qO- ipv4.icanhazip.com);shre=#http_access;rpstat=''
until [[ $shr =~ Y|y|N|n ]]; do
	read -p "Shareable RP [Y]es [N]o : " shr
done
[[ $shr =~ N|n ]] && shre=http_access && rpstat=' not'
wget -qO- https://raw.githubusercontent.com/X-DCB/Unix/master/openvpn/squid.conf | sed -e "s/#http_access/$shre/g" | sed -e "s/x.x.x.x/$MYIP/g" > /etc/squid3/squid.conf
# reload
sq=$([ -d /etc/squid ] && echo squid || echo squid3)
systemctl restart {openvpn,$sq}
clear
wget -qO- "https://raw.githubusercontent.com/X-DCB/Unix/master/banner" | bash
echo 'Openvpn Server has been restarted.'
echo 'Squid Proxy has been restarted.'
echo 'Your Squid is'$rpstat' shareable.'