#!/bin/bash
MYIP=$(wget -qO- ipv4.icanhazip.com);shre=allow;rpstat=''
until [[ $shr =~ Y|y|N|n ]]; do
	read -p "Shareable RP [Y]es [N]o : " shr
done
[[ $shr =~ N|n ]] && shre=deny && rpstat=' not'
wget -qO- https://raw.githubusercontent.com/X-DCB/Unix/master/openvpn/squid.conf | sed -e "s/xxxxx/$shre/g" | sed -e "s/x.x.x.x/$MYIP/g" > /etc/squid3/squid.conf
# reload
systemctl restart {openvpn,squid3}
clear
wget -qO- "https://raw.githubusercontent.com/X-DCB/Unix/master/banner" | bash
echo 'Openvpn Server has been restarted.'
echo 'Squid Proxy has been restarted.'
echo 'Your Squid is'$rpstat' shareable.'